### ISSUE TITLE
CI for npm publish does not work

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/deno-unknownutil#33]
https://github.com/lambdalisue/deno-unknownutil/actions/runs/5652528753

**Comment by Milly** [comment]
Use `Array.prototype.toSorted()` in tests. However, it is an error because it does not exist some environment.

**Comment by lambdalisue** [comment]
> Use Array.prototype.toSorted() in tests. However, it is an error because it does not exist some environment.

I see. We should remove it.
